global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'acblog'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'
  - job_name: 'postgresql'
    static_configs:
      - targets: [ 'postgres-exporter:9187' ]